version: '3.0'

services:
  db:
    image: mysql:8.3.0
    env_file:
      - conf/db.env
    healthcheck:
      test: "sleep 2"
  backend:
    build: ./backend
    env_file:
      - conf/db.env
      - conf/app.env
    command: "uvicorn app:app --reload --host 0.0.0.0 --port 8000"
    restart: always
    volumes:
      - ./backend/:/srv/app/:ro
    depends_on:
      db:
        condition: service_healthy
    
